### ISSUE TITLE
Per-species pages (single-page applications)

### ISSUE THREAD

**Issue by n8upham** [mammaldiversity/mammaldiversity.github.io#1]
From @jhpoelen:

- Jekyll (and other page generators) plugins (or custom scripts) can be used to generate a single page per species if desired. Jekyll slang for this functionality is "generators" (see https://jekyllrb.com/docs/plugins/generators/) . However, as I mentioned earlier, this customization is not supported via Github pages, so would introduce some friction in the maintenance/deploy process.
- You can combine the single page with dynamics (css/javascript) to render images or additional information when taxa are selected, or hide rows that do not fit some search criteria. 
- Single per-species pages are not absolutely necessary (e.g., instead links like https://mammaldiversity.org/#1234 ) can be used and dynamics can be introduced get the look 'n feel of a single page (e.g., hide other rows and show more information on selection). However, I can see, conceptually, that per-page species are easier to think about. But, ... please note the increased maintenance and deployment friction. 
- For CSS / javascript techniques to build single page apps - I'd suggest to just search around for https://en.wikipedia.org/wiki/Single-page_application : it is a well know architectural approach that has a ton of books, libraries etc built around it. Note that https://globalbioticinteractions.org uses the approach also.

**Comment by liphardt** [comment]
Addressed with commit 8cdf45784c17b54b51aff0920f1d584cd6895e7a
