### ISSUE TITLE
Extinct vs living species denoted on "taxa" and "per-species" pages

### ISSUE THREAD

**Issue by n8upham** [mammaldiversity/mammaldiversity.github.io#11]
On the taxa page (https://mammaldiversity.github.io/taxa.html), make the column be “Living species” and then an adjacent column for “Extinct species (last 500 yrs)” — this would involve parsing the current “extinct?” column (now “extinct”) and summarizing that information

Also then on the per-species permalink pages, add the fields for
`extinct	domestic	flagged	newSppSinceMSW3`

For now as 0/1 data but we could imagine forming a sentence from this, e.g., “This species is (living / extinct in the last 500 years), they live in (wild / domestic) habitats, their taxonomic status is (accepted / flagged), and they (are newly recognized since / we already recognized in) MSW3 2005.”

**Comment by liphardt** [comment]
addressed with commit 7b1c52f07910690535981b8d8e6a9ca719703ce0
