### ISSUE TITLE
Add logic for the 'parentheses' column relative to authority

### ISSUE THREAD

**Issue by n8upham** [mammaldiversity/mammaldiversity.github.io#12]
After we upload the next version (so not yet), use the binary 'parentheses' column to code "(authority, year)" vs "authority, year".

Here's an explanation:

> If the original name of the species has changed, the format is modified by placing the name of the original authority (and, for an animal name, the year of publication of the name by the original authority) in parentheses. For example, the Philippine brown deer, Rusa marianna, was originally described as Cervus mariannus by Desmarest in 1822. For this reason, this name appears as “Rusa marianna (Desmarest, 1822)” in print. The reason for the use of parentheses is that the genus name now used for this species of Philippine deer is not the same name that Desmarest originally published.

https://www.aje.com/arc/editing-tip-scientific-names-species/

**Comment by liphardt** [comment]
Okay. Keep me posted when the new spreadsheet is uploaded.

**Comment by liphardt** [comment]
Addressed with commit 178218be0fecdbde1c00c255fe1826d482e04cf4
