### ISSUE TITLE
Add a json endpoint from the data to make the site friendly for web integrations

### ISSUE THREAD

**Issue by n8upham** [mammaldiversity/mammaldiversity.github.io#2]
For example, @jhpoelen just added such an endpoint to the Open Traits Network site, and folks were pretty enthusiastic about it. See https://github.com/open-traits-network/open-traits-network.github.io/issues/109#issuecomment-618127394 .

**Comment by liphardt** [comment]
Added json endpoint with commit 7fa08b3ae25bf78ba0da4ab4dc97a97d629dc9c7
