### ISSUE TITLE
https://www.mammadiversity.org resolves to a webpage, but https://mammaldiversity.org does *not*

### ISSUE THREAD

**Issue by jhpoelen** [mammaldiversity/mammaldiversity.github.io#47]
@n8upham mentioned - 

> It could be a separate issue, but the same folks are complaining that they need to add "www" to the URL where they used to be able to just use "mammaldiversity.org" -- mentioning that here in case its also relevant. Any thoughts?

Yeah, I noticed that too. Probably a DNS related issue.

_Originally posted by @jhpoelen in https://github.com/mammaldiversity/mammaldiversity.github.io/issues/13#issuecomment-1919343436_

**Comment by JelleZijlstra** [comment]
Yes, they resolve to different IPs:

```
% host mammaldiversity.org
mammaldiversity.org has address 216.194.165.54
mammaldiversity.org mail is handled by 0 mammaldiversity.org.
% host www.mammaldiversity.org
www.mammaldiversity.org is an alias for mammaldiversity.github.io.
mammaldiversity.github.io has address 185.199.111.153
mammaldiversity.github.io has address 185.199.110.153
mammaldiversity.github.io has address 185.199.109.153
mammaldiversity.github.io has address 185.199.108.153
mammaldiversity.github.io has IPv6 address 2606:50c0:8000::153
mammaldiversity.github.io has IPv6 address 2606:50c0:8001::153
mammaldiversity.github.io has IPv6 address 2606:50c0:8002::153
mammaldiversity.github.io has IPv6 address 2606:50c0:8003::153
```

The IP behind mammaldiversity.org is owned by inmotionhosting.com, which doesn't seem to be MDD's current host. Ideally mammaldiversity.org should also be an alias (CNAME) for mammaldiversity.github.io, but if I recall correctly you can't CNAME a top-level domain.

**Comment by n8upham** [comment]
Hi @jhpoelen -- The manager of the mammaldiversity.org domain is @smaher02 of the ASM Communication Committee.  

Sean, could you help us edit the CNAME file on the InMotion server so that both "www.mammaldiversity.org" and "mammaldiversity.org" resolve to the MDD website?  As current, only the "www" version resolves properly and the other one throws an error, which multiple people have complained about since ~Jan 1, 2024.  Thanks much

**Comment by jhpoelen** [comment]
Curious to hear whether @smaher02 was able to review the DNS configuration of https://mammaldiversity.org to make sure that the A- and C- records are setup that both

https://mammaldiversity.org

and

https://www.mammaldiversity.org 

resolve to their expected GitHub hosted web pages.

**Comment by jhpoelen** [comment]
Just checked, and it appears that the https://mammaldiversity.org issue still have not been resolved.

**Comment by smaher02** [comment]
Can you show me what you get when you click 'Learn more' and 'Advanced'? I am not experiencing this error on Firefox or Edge at the moment. I had it with Chrome but click the trust page and it takes me to the site.

-Sean

Sean P. Maher
Associate Professor, Department of Biology
Director, Bull Shoals Field Station
Missouri State University
SCNC Hall 269 | 417-836-6916
he/him

________________________________

**Comment by jhpoelen** [comment]
@smaher02 thanks for asking . . . please see attached screenshot 

![image](https://github.com/mammaldiversity/mammaldiversity.github.io/assets/1084872/2fc7d722-4aad-42f0-9708-2b45502ac2e6)

**Comment by jhpoelen** [comment]
see GitHub instruction on setting up GitHub Pages using a custom domain (mammaldiversity.org in our case) - 

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by jhpoelen** [comment]
Note that 

```
$ dig www.mammaldiversity.org +nostats +nocomments +nocmd
;www.mammaldiversity.org.	IN	A
www.mammaldiversity.org. 458	IN	CNAME	mammaldiversity.org.
mammaldiversity.org.	458	IN	A	185.199.110.153
mammaldiversity.org.	458	IN	A	185.199.111.153
mammaldiversity.org.	458	IN	A	185.199.109.153
mammaldiversity.org.	458	IN	A	185.199.108.153
mammaldiversity.org.	458	IN	SOA	ns1.inmotionhosting.com. machinemessages.forum.inmotionhosting.com. 2024022009 3600 1800 1209600 86400
```

appears to look different that the example in the documentation

```
$ dig WWW.EXAMPLE.COM +nostats +nocomments +nocmd
> ;WWW.EXAMPLE.COM.                    IN      A
> WWW.EXAMPLE.COM.             3592    IN      CNAME   YOUR-USERNAME.github.io.
> YOUR-USERNAME.github.io.      43192   IN      CNAME   GITHUB-PAGES-SERVER .
> GITHUB-PAGES-SERVER .         22      IN      A       192.0.2.1
```

**Comment by jhpoelen** [comment]
@smaher02 would it be an idea to setup an account with a domain name registrar that allows multiple folks to administer the domain config? I'd say that having more than one admin, the risk of losing / misconfiguring the domain is reduced. Curious to hear your thoughts on all this.

**Comment by smaher02** [comment]
I adjusted the  www.mammaldiversity.org<http://www.mammaldiversity.org/>  CNAME record to point for to mammaldiversity.github.io.

A names still are associated with mammaldiversity.org.

In terms of adding others to access domain config, I need to check with the hosting company and see if that it is possible without providing access to the rest of our bits.

-Sean


Sean P. Maher
Associate Professor, Department of Biology
Director, Bull Shoals Field Station
Missouri State University
SCNC Hall 269 | 417-836-6916
he/him

________________________________

**Comment by jhpoelen** [comment]
@smaher02 thanks . I can confirm that the CNAME record changed - 

```
;www.mammaldiversity.org.	IN	A
www.mammaldiversity.org. 887	IN	CNAME	mammaldiversity.github.io.
mammaldiversity.github.io. 887	IN	A	185.199.108.153
mammaldiversity.github.io. 887	IN	A	185.199.110.153
mammaldiversity.github.io. 887	IN	A	185.199.111.153
mammaldiversity.github.io. 887	IN	A	185.199.109.153
```

Waiting to DNS changes to propagate.

**Comment by n8upham** [comment]
Fantastic!!  Thanks so much @smaher02 for tracking that change down and @jhpoelen for being persistent about following up about it.  Great to have that detail addressed for the long-term coherency of the MDD website.

Sean, let us know what you hear back about the shared domain config access -- that would be convenient if possible.

**Comment by jhpoelen** [comment]
it appears that the DNS changes propagated, and the certificate for https://mammaldiversity.org appears valid:

```
$ curl -I https://mammaldiversity.org/
HTTP/2 301 
server: GitHub.com
content-type: text/html
location: https://www.mammaldiversity.org/
x-github-request-id: 7306:380A14:5A254:7A5F0:66062537
accept-ranges: bytes
date: Fri, 29 Mar 2024 02:19:42 GMT
via: 1.1 varnish
age: 7
x-served-by: cache-cmh1290050-CMH
x-cache: HIT
x-cache-hits: 1
x-timer: S1711678782.285708,VS0,VE2
vary: Accept-Encoding
x-fastly-request-id: c4fd85eaa742212e28800662a5ecb6015c6feae0
content-length: 162
```

thanks @smaher02 . Am still hoping to hear your thoughts on how to make the domain management configuration accessed through some kind of group account in which trusted individual can co-manage the ```mammaldiversity.org``` domain.
