### ISSUE TITLE
I sometimes get a 404 link to `https://www.mammaldiversity.org/explore.htmlgenus=Zaglossus&species=attenboroughi&id=1000003` (notice missing `?` after `explore.html`) if I go to "Search species", start typing "Zagl", and click one of the species. Sometimes it goes to this 404 link and sometimes it correctly shows the species account.

### ISSUE THREAD

**Issue by jhpoelen** [mammaldiversity/mammaldiversity.github.io#49]
Thanks! It's inconsistent, but I sometimes get a 404 link to `https://www.mammaldiversity.org/explore.htmlgenus=Zaglossus&species=attenboroughi&id=1000003` (notice missing `?` after `explore.html`) if I go to "Search species", start typing "Zagl", and click one of the species. Sometimes it goes to this 404 link and sometimes it correctly shows the species account.

_Originally posted by @JelleZijlstra in https://github.com/mammaldiversity/mammaldiversity.github.io/issues/24#issuecomment-1948916460_

**Comment by jhpoelen** [comment]
@JelleZijlstra thanks for your pull request. I've merged your changes.

@n8upham please confirm this resolves the issue by closing #49 .

**Comment by JelleZijlstra** [comment]
Nate reported a similar but distinct issue in https://github.com/mammaldiversity/mammaldiversity.github.io/issues/24#issuecomment-1948954837. I think what's going on there is that we're already on a specific species page, then just append the URL parameters for another species at the end, instead of replacing them.

**Comment by n8upham** [comment]
The species pages are now loading, but I'm getting "https://www.mammaldiversity.org/explore.html#" as the URL initially -- with the permalink listed below, e.g.,
> Species Permalink: https://www.mammaldiversity.org/explore.html#genus=Philander&species=vossi&id=1000035

But then if I click that link, and then click another species, the permalink stays as the first species clicked -- see:

<img width="1104" alt="Screenshot 2024-02-16 at 11 28 46 AM" src="https://github.com/mammaldiversity/mammaldiversity.github.io/assets/12020947/c8f3b5b4-07e5-4e69-94ed-504369e798e2">

**Comment by jhpoelen** [comment]
@n8upham thanks for catching this. It appears that there's some timing issues that throw off the setting of the url fragments. Looking into it, and curious to hear @JelleZijlstra thoughts on this. I didn't change the code much beyond moving it around and loading from static js/mdd.js .

**Comment by jhpoelen** [comment]
@n8upham @n8upham please feel free to close this issue. Otherwise, please holler if the 404s still happen when resolving taxon info panels.

**Comment by n8upham** [comment]
All resolved now thanks to new permalink structure and code see #49 and #52
