### ISSUE TITLE
"Species ID" field not populated after new CSV uploaded

### ISSUE THREAD

**Issue by n8upham** [mammaldiversity/mammaldiversity.github.io#5]
@liphardt I broke this upon uploading a new mdd.csv file -- I thought because 'ID_number' was changed to 'id' (we want to keep the latter), but my simple fix on the explore.md page did not do the trick.  I looked elsewhere in the code, but didn't see reference to this column -- perhaps you know where to look?

Thanks (and sorry!)

**Comment by liphardt** [comment]
This is an with the BOM at the beginning of a UTF encoded CSV messing with how Ruby (Liquid) is parsing the first column. We temporarily fixed this by adding a blank first column. Leaving the issue open until a more permanent fix.

**Comment by liphardt** [comment]
Readme updated to reflect that you cannot have a BOM with 349b661906b392c8fdb29f069475145568bed761
