### ISSUE TITLE
taxon pages without original name entries do not load as expected

### ISSUE THREAD

**Issue by jhpoelen** [mammaldiversity/mammaldiversity.github.io#54]
https://www.mammaldiversity.org/explore.html#1000009 loads ok, but https://www.mammaldiversity.org/explore.html#1000718 does not. 

Pull request #53 fixes this issue. This issue was introduced last week in a recent refactoring.

You can see the error logs in the console display things like:

```
Uncaught TypeError: speciesData.originalNameCombination is null
    renderSpeciesPage https://www.mammaldiversity.org/js/filter.js:78
    populateSpeciesInfo https://www.mammaldiversity.org/js/filter.js:206
    populateSpeciesInfo https://www.mammaldiversity.org/js/filter.js:202
    loadSpeciesById https://www.mammaldiversity.org/js/filter.js:592
    loadMDD https://www.mammaldiversity.org/js/filter.js:587
    loadSpeciesById https://www.mammaldiversity.org/js/filter.js:591
    fillSpeciesInfo https://www.mammaldiversity.org/js/filter.js:597
    onclick https://www.mammaldiversity.org/explore.html#1000009:1
```

the root cause was that Jekyll sets null values to null, whereas the previous javascript library used to load csv files set null values to an empty string (e.g., ```""```). 

![image](https://github.com/mammaldiversity/mammaldiversity.github.io/assets/1084872/bfa08d30-fb50-4678-b163-eb02b3d002a3)

**Comment by n8upham** [comment]
OK nice, thanks for this @jhpoelen -- yes, I just noticed this behavior searching for "Poemys" and not getting the species page to load (and got a bug report about "Lepus"), so I'm glad to see that you already have the solution!  I'll review the pull request locally and then let you know

**Comment by n8upham** [comment]
Fixed now, thanks
