### ISSUE TITLE
MDD is slow / not loading for some users 

### ISSUE THREAD

**Issue by n8upham** [mammaldiversity/mammaldiversity.github.io#55]
Any idea @jhpoelen ?
From user in Alaska (multiple browser types):
![IMG_20240222_195601_01](https://github.com/mammaldiversity/mammaldiversity.github.io/assets/12020947/3f68a92a-11b3-4545-903f-7b2eb8192828)

Thanks

**Comment by JelleZijlstra** [comment]
That might mean excessive JavaScript code execution, e.g. an infinite loop. Did they share what they did exactly to get into that state?

**Comment by jhpoelen** [comment]
Would you like me to spend time time optimizing the web page load performance?

**Comment by jhpoelen** [comment]
Also, would you happen to know if this a recent issue, or something that started happening recently?

**Comment by jhpoelen** [comment]
I took a peek at performance and found a way to make the map loading a little friendlier.

**Comment by jhpoelen** [comment]
see https://github.com/mammaldiversity/mammaldiversity.github.io/pull/56 for proposed changes.

**Comment by n8upham** [comment]
This seems a LOT faster now -- nearly no delay on loading from my end in Arizona.  Thanks for this @jhpoelen -- lazy loading appears to be the needed trick
