### ISSUE TITLE
taxon pages no longer rendering (e.g., https://www.mammaldiversity.org/taxon/1000065)

### ISSUE THREAD

**Issue by jhpoelen** [mammaldiversity/mammaldiversity.github.io#69]
After recent changes, the taxon pages no longer appear to render their html landing pages.

For instance, https://www.mammaldiversity.org/taxon/1000065

generated a web page with the html menu, and no visible content.

![image](https://github.com/user-attachments/assets/35cedc0d-9bf7-4ba7-a4a0-76e16f3f74bb)

**Comment by jhpoelen** [comment]
The root cause (or at least one of them) appears to be a javascript coding error 

```
Uncaught TypeError: speciesData.originalNameCombination.split(...)[1] is undefined
    renderSpeciesPage https://www.mammaldiversity.org/js/filter.js:145
    populateSpeciesInfo https://www.mammaldiversity.org/js/filter.js:343
    populateSpeciesInfo https://www.mammaldiversity.org/js/filter.js:339
    loadSpeciesById https://www.mammaldiversity.org/js/filter.js:757
    loadMDD https://www.mammaldiversity.org/js/filter.js:752
    loadSpeciesById https://www.mammaldiversity.org/js/filter.js:756
    loadSpeciesPage https://www.mammaldiversity.org/taxon/1000003:69
filter.js:145:43
```

Did y'all consider implementing some unit tests to cover this kind of stuff?

**Comment by jhpoelen** [comment]
Perhaps already fixed via https://github.com/mammaldiversity/mammaldiversity.github.io/pull/68 , but haven't tried myself. 

Just wanted to make sure to report this issue. 

Hope this helps.

**Comment by JelleZijlstra** [comment]
#68 fixes this. Agree better testing would be helpful.

**Comment by jhpoelen** [comment]
Ok, perhaps this would be a good time to add some unit tests ; )

Happy to review them as part of the pull request.
